 receivers:
     otlp:
       protocols:
         grpc:
           endpoint: 0.0.0.0:4317
         http:
           endpoint: 0.0.0.0:4318
   
   processors:
     batch:
   
   exporters:
     logging:
       loglevel: debug
     mysql:
       dsn: "root:1234@tcp(mysql:3306)/traces"
       timeout: 10s
       sql_statement: "INSERT INTO traces (...) VALUES (...)"
   
   service:
     pipelines:
       traces:
         receivers: [otlp]
         processors: [batch]
         exporters: [logging, mysql]